# Generated by Django 3.1.2 on 2021-12-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20211224_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='in_main',
            new_name='is_main',
        ),
    ]
